"""Add journal_entry relationship to PayrollLog

Revision ID: 1cda84eb27b5
Revises: b979536ce29f
Create Date: 2025-10-18 09:47:00.350142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cda84eb27b5'
down_revision = 'b979536ce29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_entry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payroll_log_journal_entry', 'journal_entry', ['journal_entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payroll_log_journal_entry', type_='foreignkey')
        batch_op.drop_column('journal_entry_id')

    # ### end Alembic commands ###
