"""Initial database schema

Revision ID: 203a003568cc
Revises:
Create Date: 2025-10-12 12:30:13.794454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203a003568cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_account')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('normal_balance', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['name', 'tenant_id'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('code')
        batch_op.drop_column('account_type')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('salary', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('base_salary')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('account_id')
        batch_op.drop_column('debit')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('credit')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('source')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount_requested', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('term_months', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('signature_image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('requested_term')
        batch_op.drop_column('application_date')
        batch_op.drop_column('signed_document_url')
        batch_op.drop_column('signature_status')
        batch_op.drop_column('requested_amount')

    with op.batch_alter_table('loan_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=False))
        batch_op.create_unique_constraint(None, ['name', 'tenant_id'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('commission_type')
        batch_op.drop_column('admin_commission_rate')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('close_date')
        batch_op.drop_column('lead_id')
        batch_op.drop_column('loan_application_id')
        batch_op.drop_column('estimated_amount')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('registered_by_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('journal_entry_id', sa.Integer(), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['registered_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'journal_entry', ['journal_entry_id'], ['id'])
        batch_op.drop_column('recorded_by_user_id')
        batch_op.drop_column('amount')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('loan_application_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['name', 'tenant_id'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('journal_entry_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'journal_entry', ['journal_entry_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email', 'tenant_id'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amount')
        batch_op.drop_column('type')
        batch_op.drop_column('account_id')
        batch_op.drop_column('journal_entry_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_application_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'loan_application', ['loan_application_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('recorded_by_user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recorded_by_user_id'], ['id'])
        batch_op.alter_column('payment_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('journal_entry_id')
        batch_op.drop_column('registered_by_id')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('loan_application_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('close_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'loan_application', ['loan_application_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('loan_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_commission_rate', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('commission_type', sa.VARCHAR(length=1), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('signature_status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('signed_document_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('application_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('requested_term', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('signed_at')
        batch_op.drop_column('signature_image')
        batch_op.drop_column('term_months')
        batch_op.drop_column('amount_requested')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('debit', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('date')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('base_salary', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('hire_date')
        batch_op.drop_column('salary')
        batch_op.drop_column('full_name')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('normal_balance')
        batch_op.drop_column('category')
        batch_op.drop_column('tenant_id')

    op.create_table('_alembic_tmp_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('normal_balance', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_account_tenant')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name=op.f('uq_account_name_tenant'))
    )
    # ### end Alembic commands ###
