"""Add Banking Reconciliation models

Revision ID: 2e8c7aab9eec
Revises:
Create Date: 2025-10-15 19:58:04.601677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e8c7aab9eec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_assignment')
    op.drop_table('signature_request')
    op.drop_table('invoice_item')
    op.drop_table('invoice')
    op.drop_table('client_company')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('hire_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('employee_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.alter_column('hire_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('client_company',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('client_company_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_company_pkey'),
    sa.UniqueConstraint('name', name='client_company_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('invoice_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fiscal_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fiscal_series', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fiscal_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='invoice_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_pkey'),
    sa.UniqueConstraint('fiscal_id', name='invoice_fiscal_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('invoice_item_invoice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_item_pkey'))
    )
    op.create_table('signature_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loan_application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_request_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('signer_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_application.id'], name=op.f('signature_request_loan_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('signature_request_pkey')),
    sa.UniqueConstraint('provider_request_id', name=op.f('signature_request_provider_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('temporary_assignment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('position_in_client', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('assignment_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], name=op.f('temporary_assignment_client_company_id_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('temporary_assignment_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('temporary_assignment_pkey'))
    )
    # ### end Alembic commands ###
