"""Initial migration

Revision ID: 5511abd98c49
Revises:
Create Date: 2025-10-16 04:38:56.378444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5511abd98c49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=False, server_default='SV'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
