"""Add carpentry module models

Revision ID: a1b2c3d4e5f6
Revises: a1b2c3d4e5f5
Create Date: 2025-10-23 08:23:27.787773
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'a1b2c3d4e5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Carpentry Projects
    op.create_table('carpentry_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, default='Cotización'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carpentry_project_status'), 'carpentry_project', ['status'], unique=False)
    op.create_index(op.f('ix_carpentry_project_tenant_id'), 'carpentry_project', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_carpentry_project_created_at'), 'carpentry_project', ['created_at'], unique=False)
    
    # Carpentry Tasks
    op.create_table('carpentry_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, default='Pendiente'),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['carpentry_project.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carpentry_task_status'), 'carpentry_task', ['status'], unique=False)
    op.create_index(op.f('ix_carpentry_task_project_id'), 'carpentry_task', ['project_id'], unique=False)
    op.create_index(op.f('ix_carpentry_task_tenant_id'), 'carpentry_task', ['tenant_id'], unique=False)
    
    # Carpentry Materials
    op.create_table('carpentry_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('stock_level', sa.Float(), nullable=False, default=0.0),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('min_stock_level', sa.Float(), nullable=True, default=0.0),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carpentry_material_tenant_id'), 'carpentry_material', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_carpentry_material_name'), 'carpentry_material', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_carpentry_material_name'), table_name='carpentry_material')
    op.drop_index(op.f('ix_carpentry_material_tenant_id'), table_name='carpentry_material')
    op.drop_table('carpentry_material')
    
    op.drop_index(op.f('ix_carpentry_task_tenant_id'), table_name='carpentry_task')
    op.drop_index(op.f('ix_carpentry_task_project_id'), table_name='carpentry_task')
    op.drop_index(op.f('ix_carpentry_task_status'), table_name='carpentry_task')
    op.drop_table('carpentry_task')
    
    op.drop_index(op.f('ix_carpentry_project_created_at'), table_name='carpentry_project')
    op.drop_index(op.f('ix_carpentry_project_tenant_id'), table_name='carpentry_project')
    op.drop_index(op.f('ix_carpentry_project_status'), table_name='carpentry_project')
    op.drop_table('carpentry_project')
    # ### end Alembic commands ###