name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          conda init bash

      - name: Create environment
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda env create -f environment.yml

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          conda run -n prestamos-backend flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n prestamos-backend flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda run -n prestamos-backend pytest --tb=short
